# Generated by Django 5.2.16 on 2026-07-12 10:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterscan', '0001_initial'),
        ('eveonline', '0025_remove_evecharacter_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can access this app and apply as a recruit'), ('recruiter', 'Can view and manage recruitment applications'))},
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eve_character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eveonline.evecharacter', verbose_name='EVE character')),
            ],
            options={
                'ordering': ['-updated_at'],
                'default_permissions': (),
            },
        ),
    ]
