# Generated by Django 5.2.16 on 2026-07-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characterscan', '0002_alter_general_options_recruit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruit',
            options={'ordering': ['-updated_at'], 'verbose_name': 'recruit', 'verbose_name_plural': 'recruits'},
        ),
    ]
