# Generated by Django 5.2.16 on 2026-07-12 20:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterscan', '0003_alter_recruit_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('applied', 'Aangemeld'), ('accepted', 'Aangenomen'), ('rejected', 'Afgewezen'), ('new', 'Heropend'), ('note', 'Notitie')], max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='characterscan.recruit')),
            ],
            options={
                'verbose_name': 'recruit log entry',
                'verbose_name_plural': 'recruit log entries',
                'ordering': ['-created_at'],
                'default_permissions': (),
            },
        ),
    ]
