# Generated by Django 5.2.16 on 2026-07-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterscan', '0004_recruitlogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='known_bad_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recruit',
            name='last_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruit',
            name='last_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruit',
            name='last_verdict',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='recruitlogentry',
            name='action',
            field=models.CharField(choices=[('applied', 'Aangemeld'), ('accepted', 'Aangenomen'), ('rejected', 'Afgewezen'), ('new', 'Heropend'), ('note', 'Notitie'), ('alert', 'Waarschuwing')], max_length=20),
        ),
    ]
