# Generated by Django 5.2.16 on 2026-07-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterscan', '0005_recruit_known_bad_flags_recruit_last_scanned_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_webhook', models.URLField(blank=True, default='', help_text='Voor aanmeldingen en rode-vlag-meldingen. Leeg = notificaties uit. (Discord: Kanaal → Integraties → Webhooks → Nieuwe webhook.)', max_length=500, verbose_name='Discord-webhook-URL')),
                ('notify_new_application', models.BooleanField(default=True, verbose_name='Melden bij nieuwe aanmelding')),
                ('notify_alerts', models.BooleanField(default=True, verbose_name='Melden bij nieuwe rode vlag (monitoring)')),
            ],
            options={
                'verbose_name': 'instellingen',
                'verbose_name_plural': 'instellingen',
                'permissions': (('manage_settings', 'Can manage Character Scan settings'),),
                'default_permissions': (),
            },
        ),
    ]
