# Generated by Django 5.2.16 on 2026-07-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterscan', '0006_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='min_jump_clones',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Min. aantal jump clones'),
        ),
        migrations.AddField(
            model_name='settings',
            name='staging_name',
            field=models.CharField(blank=True, default='', help_text="Bijv. 'BKG-Q2 - Insidious Prime'. Getoond bij de clone-stap.", max_length=200, verbose_name='Staging (weergavenaam)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='staging_system_id',
            field=models.PositiveIntegerField(blank=True, help_text='Home/death-clone in dit systeem = stap afgevinkt.', null=True, verbose_name='Staging solar system id'),
        ),
    ]
