# Generated by Django 5.2.16 on 2026-07-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterscan', '0007_settings_min_jump_clones_settings_staging_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='extra_enemy_ids',
            field=models.TextField(blank=True, default='', help_text='Handmatige aanvulling op de automatische vijandenlijst: character-, corp- of alliance-ids (één per regel of komma-gescheiden).', verbose_name='Extra vijand-ids'),
        ),
        migrations.AddField(
            model_name='settings',
            name='injector_alert',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Waarschuwing vanaf dit aantal gekochte Large injectors. Leeg = standaard 5.', null=True, verbose_name='Skill-injector-drempel'),
        ),
        migrations.AddField(
            model_name='settings',
            name='trusted_link_domains',
            field=models.TextField(blank=True, default='', help_text="Eén per regel (of komma-gescheiden). Links hierheen tellen niet als 'externe link' in de mail-scan. Bijv. auth.jouwalliance.org", verbose_name='Vertrouwde link-domeinen'),
        ),
        migrations.AddField(
            model_name='settings',
            name='wallet_alert_isk',
            field=models.BigIntegerField(blank=True, help_text='Grote/verdachte ISK-bewegingen boven dit bedrag. Leeg = standaard 1 miljard.', null=True, verbose_name='Wallet-alarmdrempel (ISK)'),
        ),
    ]
