# Generated by Django 5.2.16 on 2026-07-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characterscan', '0008_settings_extra_enemy_ids_settings_injector_alert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='min_jump_clones',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='staging_name',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='staging_system_id',
        ),
    ]
