# Generated by Django 5.2.16 on 2026-07-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterscan', '0009_remove_settings_min_jump_clones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='last_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
