# Generated by Django 5.2.16 on 2026-07-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterscan', '0010_recruit_last_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In behandeling'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='recruitlogentry',
            name='action',
            field=models.CharField(choices=[('applied', 'Aangemeld'), ('in_progress', 'In behandeling genomen'), ('accepted', 'Aangenomen'), ('rejected', 'Afgewezen'), ('new', 'Heropend'), ('note', 'Notitie'), ('alert', 'Waarschuwing')], max_length=20),
        ),
    ]
