# Generated by Django 5.2.16 on 2026-07-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterscan', '0012_recruit_handled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='show_actions_on_done',
            field=models.BooleanField(default=False, help_text='Uit (standaard): bij afgeronde (aangenomen/afgewezen) aanmeldingen zijn de ✓/✕/⏳-knoppen verborgen. Aan: toon ze ook daar, zodat je de status kunt wijzigen.', verbose_name='Actie-knoppen tonen bij afgeronde aanmeldingen'),
        ),
    ]
