# Generated by Django 5.2.16 on 2026-07-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterscan', '0013_settings_show_actions_on_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='wait_alert_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Markeer aanmeldingen die zó lang op een beslissing wachten (nieuw/in behandeling). Leeg = standaard 48 uur.', null=True, verbose_name='Wachttijd-alarmdrempel (uren)'),
        ),
    ]
