# Generated by Django 5.2.16 on 2026-08-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterscan', '0014_settings_wait_alert_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='onboarding_groups',
            field=models.TextField(blank=True, default='', help_text='Groepen die een nieuw lid moet hebben — één per regel of komma-gescheiden. Leeg = minstens één groep volstaat.', verbose_name='Verplichte groepen'),
        ),
        migrations.AddField(
            model_name='settings',
            name='onboarding_new_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Hoe lang een aangenomen recruit op het onboarding-overzicht als nieuw lid meetelt. Leeg = standaard 30 dagen.', null=True, verbose_name='Nieuw lid tot (dagen)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='onboarding_state',
            field=models.CharField(blank=True, default='', help_text='Naam van de AA-state die een volwaardig lid hoort te hebben, bijv. Member. Leeg = elke state behalve Guest is goed.', max_length=50, verbose_name='Verwachte state'),
        ),
    ]
